# Generated by Django 3.2.9 on 2022-01-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('version', models.CharField(max_length=20, null=True)),
                ('shop', models.CharField(max_length=70)),
                ('price', models.IntegerField()),
                ('url', models.URLField(null=True)),
                ('date', models.DateField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stock', models.BooleanField(default=False)),
            ],
        ),
    ]
